#!/usr/bin/env node
// `npm run setup` — interactive first-run wizard.
//
// 1. Detects which agent CLIs are installed (claude, hermes, openclaw, ollama).
// 2. Auto-detects the operator's Obsidian vault path, prompts to confirm or override.
// 3. Writes ~/.agentic-os/config.yaml using YAML.
// 4. Creates ~/.agentic-os/audit/ for the JSONL log to land in.

import readline from "node:readline/promises";
import { execSync } from "node:child_process";
import { promises as fs, existsSync } from "node:fs";
import path from "node:path";
import os from "node:os";

const ANSI = {
  reset: "\x1b[0m",
  dim:   "\x1b[2m",
  bold:  "\x1b[1m",
  green: "\x1b[32m",
  yel:   "\x1b[33m",
  blue:  "\x1b[36m",
  red:   "\x1b[31m",
};

const HOME = os.homedir();
const CFG_DIR = path.join(HOME, ".agentic-os");
const CFG_PATH = path.join(CFG_DIR, "config.yaml");
const AUDIT_DIR = path.join(CFG_DIR, "audit");

function which(bin) {
  try {
    const out = execSync(`command -v ${bin}`, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
    return out || null;
  } catch { return null; }
}

function detectVaultCandidates() {
  const candidates = [
    path.join(HOME, "Documents", "Obsidian", "Rex-Knowledge"),
    path.join(HOME, "Documents", "Obsidian Vault"),
    path.join(HOME, "Obsidian"),
    path.join(HOME, "Obsidian Vault"),
  ];
  // Also any folder under ~/Documents/Obsidian.
  const objDir = path.join(HOME, "Documents", "Obsidian");
  if (existsSync(objDir)) {
    try {
      for (const name of execSync(`ls ${JSON.stringify(objDir)}`).toString().split("\n").filter(Boolean)) {
        candidates.push(path.join(objDir, name));
      }
    } catch { /* ignore */ }
  }
  return candidates.filter((p) => existsSync(p) && existsSync(path.join(p, ".obsidian")));
}

async function main() {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q, def) =>
    rl.question(`${q}${def ? ` ${ANSI.dim}[${def}]${ANSI.reset}` : ""} `).then((a) => a.trim() || def || "");

  console.log(`\n${ANSI.bold}agentic-os setup${ANSI.reset}  ${ANSI.dim}— writes ~/.agentic-os/config.yaml${ANSI.reset}\n`);

  // 1. Agent detection
  console.log(`${ANSI.bold}1. detect agents${ANSI.reset}`);
  const agents = ["claude", "hermes", "openclaw", "ollama"];
  let foundCount = 0;
  for (const a of agents) {
    const p = which(a);
    if (p) {
      console.log(`  ${ANSI.green}✓${ANSI.reset} ${a.padEnd(10)} ${ANSI.dim}${p}${ANSI.reset}`);
      foundCount++;
    } else {
      console.log(`  ${ANSI.dim}—${ANSI.reset} ${a.padEnd(10)} ${ANSI.dim}not on PATH${ANSI.reset}`);
    }
  }
  if (foundCount === 0) {
    console.log(`  ${ANSI.yel}note:${ANSI.reset} no agent CLIs detected. You can still install one later.`);
  }
  console.log();

  // 2. Vault path
  console.log(`${ANSI.bold}2. obsidian vault path${ANSI.reset}`);
  const candidates = detectVaultCandidates();
  let defaultVault = candidates[0] ?? "";
  if (candidates.length > 0) {
    console.log(`  detected vault candidates:`);
    candidates.forEach((p, i) => console.log(`    ${i + 1}. ${p}`));
  } else {
    console.log(`  ${ANSI.dim}(no obsidian vaults auto-detected)${ANSI.reset}`);
  }
  const vaultPath = await ask(`\n  vault.root:`, defaultVault);
  if (!vaultPath) {
    console.log(`\n${ANSI.red}× vault path is required.${ANSI.reset} Aborting.`);
    rl.close();
    process.exit(2);
  }
  if (!existsSync(vaultPath)) {
    console.log(`\n${ANSI.yel}warning:${ANSI.reset} ${vaultPath} does not exist yet. You'll need to create it before starting the dev server.`);
  }
  console.log();

  // 3. Default agent
  console.log(`${ANSI.bold}3. default agent for the dashboard${ANSI.reset}`);
  const installed = agents.filter((a) => which(a));
  const defaultAgentSuggestion = installed.includes("claude") ? "claude-code" : (installed[0] ?? "claude-code");
  const defaultAgent = await ask(`  agents.default:`, defaultAgentSuggestion);
  console.log();

  // 4. Confirm + write
  if (existsSync(CFG_PATH)) {
    const overwrite = await ask(`${ANSI.yel}config.yaml already exists. overwrite?${ANSI.reset} (y/N)`, "N");
    if (!/^y/i.test(overwrite)) {
      console.log(`Aborted. existing config at ${CFG_PATH} kept.`);
      rl.close();
      return;
    }
  }

  await fs.mkdir(CFG_DIR, { recursive: true });
  await fs.mkdir(AUDIT_DIR, { recursive: true });

  const cfg =
    `# Generated by \`npm run setup\` on ${new Date().toISOString()}\n` +
    `vault:\n  root: ${vaultPath}\n\nagents:\n  default: ${defaultAgent}\n`;
  await fs.writeFile(CFG_PATH, cfg, "utf8");

  console.log(`${ANSI.green}✓${ANSI.reset} wrote ${CFG_PATH}`);
  console.log(`${ANSI.green}✓${ANSI.reset} ensured ${AUDIT_DIR}/\n`);
  console.log(`${ANSI.bold}done.${ANSI.reset}  Next:`);
  console.log(`  ${ANSI.blue}npm run dev${ANSI.reset}  →  http://127.0.0.1:3000\n`);

  rl.close();
}

main().catch((e) => {
  console.error(`\n${ANSI.red}× setup failed:${ANSI.reset}`, e.message);
  process.exit(1);
});
